import type VehicleProps from "@/interfaces/vehicleProps";
import {
  BodyType,
  Category,
  Transmition,
  Fuel,
  DriveTrain,
  Status,
} from "@/interfaces/vehicleProps";

const mockProducts: VehicleProps[] = [
  {
    id: 1,
    title: "Toyota Corolla 2023",
    make: "Toyota",
    model: "Corolla",
    year: 2023,
    trim: "LE",
    bodytype: BodyType.Sedan,
    category: Category.Compact,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Blanco",
    seats: 5,
    country: "México",
    city: "Monterrey",
    state: "Monterrey",
    lat: 25.6866,
    lng: -100.3161,
    pricePerHour: 150,
    pricePerDay: 800,
    pricePerWeek: 4500,
    deposit: 5000,
    kmIncludedPerDay: 200,
    pricePerExtraKm: 5,
    minHours: 4,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules: "No fumar, no mascotas",
    description: "Sedán compacto confiable y económico",
    photo:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 2,
    title: "Honda CR-V 2024",
    make: "Honda",
    model: "CR-V",
    year: 2024,
    trim: "EX",
    bodytype: BodyType.Suv,
    category: Category.Suv,
    transmission: Transmition.Automatic,
    fuel: Fuel.Hybrid,
    drivetrain: DriveTrain.AWD,
    color: "Negro",
    seats: 5,
    country: "México",
    city: "Guadalajara",
    state: "Guadalajara",
    lat: 20.6597,
    lng: -103.3496,
    pricePerHour: 200,
    pricePerDay: 1100,
    pricePerWeek: 6500,
    deposit: 7000,
    kmIncludedPerDay: 250,
    pricePerExtraKm: 6,
    minHours: 4,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: "No fumar",
    description: "SUV híbrida espaciosa y eficiente",
    photo:
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 4,
    title: "Nissan Versa 2022",
    make: "Nissan",
    model: "Versa",
    year: 2022,
    trim: "Sense",
    bodytype: BodyType.Sedan,
    category: Category.Economy,
    transmission: Transmition.Manual,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Rojo",
    seats: 5,
    country: "México",
    city: "Acapulco",
    state: "Guerrero",
    lat: 16.8531,
    lng: -99.8237,
    pricePerHour: 120,
    pricePerDay: 650,
    pricePerWeek: 3800,
    deposit: 4000,
    kmIncludedPerDay: 150,
    pricePerExtraKm: 4,
    minHours: 3,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules: "No fumar, no mascotas",
    description: "Sedán económico ideal para ciudad",
    photo:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 5,
    title: "Mazda CX-5 2024",
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    trim: "Touring",
    bodytype: BodyType.Suv,
    category: Category.Suv,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.AWD,
    color: "Azul",
    seats: 5,
    country: "México",
    city: "Monterrey",
    state: "Monterrey",
    lat: 25.6866,
    lng: -100.3161,
    pricePerHour: 180,
    pricePerDay: 1000,
    pricePerWeek: 5800,
    deposit: 6500,
    kmIncludedPerDay: 220,
    pricePerExtraKm: 6,
    minHours: 4,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: "No fumar",
    description: "SUV elegante con excelente manejo",
    photo:
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 7,
    title: "Tesla Model 3 2024",
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    trim: "Long Range",
    bodytype: BodyType.Sedan,
    category: Category.Electric,
    transmission: Transmition.Automatic,
    fuel: Fuel.Electric,
    drivetrain: DriveTrain.AWD,
    color: "Blanco Perla",
    seats: 5,
    country: "México",
    city: "Monterrey",
    state: "Monterrey",
    lat: 25.6866,
    lng: -100.3161,
    pricePerHour: 300,
    pricePerDay: 1800,
    pricePerWeek: 10500,
    deposit: 15000,
    kmIncludedPerDay: 400,
    pricePerExtraKm: 8,
    minHours: 4,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: "Cargo completo requerido al regresar",
    description: "Sedán eléctrico de lujo con autopilot",
    photo:
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 8,
    title: "Chevrolet Silverado 2023",
    make: "Chevrolet",
    model: "Silverado",
    year: 2023,
    trim: "LT",
    bodytype: BodyType.Pickup,
    category: Category.Pickup,
    transmission: Transmition.Automatic,
    fuel: Fuel.Diesel,
    drivetrain: DriveTrain.WD4,
    color: "Negro",
    seats: 5,
    country: "México",
    city: "Hermosillo",
    state: "Sonora",
    lat: 29.0729,
    lng: -110.9559,
    pricePerHour: 280,
    pricePerDay: 1500,
    pricePerWeek: 8800,
    deposit: 11000,
    kmIncludedPerDay: 350,
    pricePerExtraKm: 7,
    minHours: 6,
    minDriverAge: 26,
    insuranceIncluded: true,
    rules: "Experiencia con pickups requerida",
    description: "Pickup diesel para trabajo pesado",
    photo:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 9,
    title: "Kia Forte 2023",
    make: "Kia",
    model: "Forte",
    year: 2023,
    trim: "LX",
    bodytype: BodyType.Sedan,
    category: Category.Compact,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Plata",
    seats: 5,
    country: "México",
    city: "Acapulco",
    state: "Guerrero",
    lat: 16.8531,
    lng: -99.8237,
    pricePerHour: 140,
    pricePerDay: 750,
    pricePerWeek: 4200,
    deposit: 4500,
    kmIncludedPerDay: 180,
    pricePerExtraKm: 4,
    minHours: 4,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules: "No fumar",
    description: "Sedán moderno con garantía extendida",
    photo:
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 10,
    title: "Hyundai Tucson 2024",
    make: "Hyundai",
    model: "Tucson",
    year: 2024,
    trim: "SEL",
    bodytype: BodyType.Suv,
    category: Category.Suv,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.AWD,
    color: "Rojo",
    seats: 5,
    country: "México",
    city: "Guadalajara",
    state: "Guadalajara",
    lat: 20.6597,
    lng: -103.3496,
    pricePerHour: 190,
    pricePerDay: 1050,
    pricePerWeek: 6000,
    deposit: 6800,
    kmIncludedPerDay: 230,
    pricePerExtraKm: 6,
    minHours: 4,
    minDriverAge: 23,
    insuranceIncluded: true,
    rules: "No fumar, no mascotas",
    description: "SUV compacta con diseño moderno",
    photo:
      "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 11,
    title: "Honda Civic 2023",
    make: "Honda",
    model: "Civic",
    year: 2023,
    trim: "Sport",
    bodytype: BodyType.Hatchback,
    category: Category.Compact,
    transmission: Transmition.Manual,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Azul Deportivo",
    seats: 5,
    country: "México",
    city: "Monterrey",
    state: "Monterrey",
    lat: 25.6866,
    lng: -100.3161,
    pricePerHour: 170,
    pricePerDay: 900,
    pricePerWeek: 5200,
    deposit: 6000,
    kmIncludedPerDay: 210,
    pricePerExtraKm: 5,
    minHours: 4,
    minDriverAge: 22,
    insuranceIncluded: true,
    rules: "No fumar",
    description: "Hatchback deportivo y eficiente",
    photo:
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 13,
    title: "BMW 320i 2023",
    make: "BMW",
    model: "320i",
    year: 2023,
    trim: "M Sport",
    bodytype: BodyType.Sedan,
    category: Category.Premium,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.RWD,
    color: "Negro",
    seats: 5,
    country: "México",
    city: "Guadalajara",
    state: "Guadalajara",
    lat: 20.6597,
    lng: -103.3496,
    pricePerHour: 350,
    pricePerDay: 2000,
    pricePerWeek: 12000,
    deposit: 18000,
    kmIncludedPerDay: 300,
    pricePerExtraKm: 10,
    minHours: 6,
    minDriverAge: 27,
    insuranceIncluded: true,
    rules: "Licencia con 5 años de antigüedad, no fumar",
    description: "Sedán de lujo con desempeño deportivo",
    photo:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 14,
    title: "Nissan Kicks 2023",
    make: "Nissan",
    model: "Kicks",
    year: 2023,
    trim: "Advance",
    bodytype: BodyType.Suv,
    category: Category.Compact,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Naranja",
    seats: 5,
    country: "México",
    city: "Acapulco",
    state: "Guerrero",
    lat: 16.8531,
    lng: -99.8237,
    pricePerHour: 150,
    pricePerDay: 800,
    pricePerWeek: 4600,
    deposit: 5000,
    kmIncludedPerDay: 190,
    pricePerExtraKm: 5,
    minHours: 4,
    minDriverAge: 21,
    insuranceIncluded: true,
    rules: "No fumar, no mascotas",
    description: "Crossover urbana ideal para la ciudad",
    photo:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 16,
    title: "Volkswagen Transporter 2023",
    make: "Volkswagen",
    model: "Transporter",
    year: 2023,
    trim: "Kombi",
    bodytype: BodyType.Van,
    category: Category.Van,
    transmission: Transmition.Manual,
    fuel: Fuel.Diesel,
    drivetrain: DriveTrain.RWD,
    color: "Blanco",
    seats: 9,
    country: "México",
    city: "Guadalajara",
    state: "Guadalajara",
    lat: 20.6597,
    lng: -103.3496,
    pricePerHour: 220,
    pricePerDay: 1200,
    pricePerWeek: 7000,
    deposit: 8000,
    kmIncludedPerDay: 280,
    pricePerExtraKm: 6,
    minHours: 6,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: "No fumar, licencia tipo A",
    description: "Van espaciosa para grupos",
    photo:
      "https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 17,
    title: "Mazda 3 2023",
    make: "Mazda",
    model: "3",
    year: 2023,
    trim: "i Grand Touring",
    bodytype: BodyType.Hatchback,
    category: Category.Compact,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.FWD,
    color: "Gris Titanio",
    seats: 5,
    country: "México",
    city: "Hermosillo",
    state: "Sonora",
    lat: 29.0729,
    lng: -110.9559,
    pricePerHour: 165,
    pricePerDay: 880,
    pricePerWeek: 5000,
    deposit: 5500,
    kmIncludedPerDay: 200,
    pricePerExtraKm: 5,
    minHours: 4,
    minDriverAge: 22,
    insuranceIncluded: true,
    rules: "No fumar",
    description: "Hatchback premium con diseño elegante",
    photo:
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 18,
    title: "Jeep Wrangler 2024",
    make: "Jeep",
    model: "Wrangler",
    year: 2024,
    trim: "Sahara",
    bodytype: BodyType.Suv,
    category: Category.Suv,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.WD4,
    color: "Verde Olivo",
    seats: 5,
    country: "México",
    city: "Acapulco",
    state: "Guerrero",
    lat: 16.8531,
    lng: -99.8237,
    pricePerHour: 280,
    pricePerDay: 1600,
    pricePerWeek: 9500,
    deposit: 12000,
    kmIncludedPerDay: 250,
    pricePerExtraKm: 8,
    minHours: 6,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: "Experiencia con 4x4 recomendada",
    description: "SUV todoterreno legendaria",
    photo:
      "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 19,
    title: "Audi A4 2024",
    make: "Audi",
    model: "A4",
    year: 2024,
    trim: "Premium Plus",
    bodytype: BodyType.Sedan,
    category: Category.Premium,
    transmission: Transmition.Automatic,
    fuel: Fuel.Gasoline,
    drivetrain: DriveTrain.AWD,
    color: "Plata",
    seats: 5,
    country: "México",
    city: "Monterrey",
    state: "Monterrey",
    lat: 25.6866,
    lng: -100.3161,
    pricePerHour: 380,
    pricePerDay: 2200,
    pricePerWeek: 13000,
    deposit: 20000,
    kmIncludedPerDay: 280,
    pricePerExtraKm: 11,
    minHours: 6,
    minDriverAge: 27,
    insuranceIncluded: true,
    rules: "Licencia con antigüedad, no fumar",
    description: "Sedán alemán de lujo con tecnología",
    photo:
      "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
  {
    id: 20,
    title: "Toyota Hilux 2023",
    make: "Toyota",
    model: "Hilux",
    year: 2023,
    trim: "SR5",
    bodytype: BodyType.Pickup,
    category: Category.Pickup,
    transmission: Transmition.Manual,
    fuel: Fuel.Diesel,
    drivetrain: DriveTrain.WD4,
    color: "Plata",
    seats: 5,
    country: "México",
    city: "Hermosillo",
    state: "Sonora",
    lat: 29.0729,
    lng: -110.9559,
    pricePerHour: 240,
    pricePerDay: 1300,
    pricePerWeek: 7500,
    deposit: 9000,
    kmIncludedPerDay: 320,
    pricePerExtraKm: 7,
    minHours: 6,
    minDriverAge: 25,
    insuranceIncluded: true,
    rules: "Licencia vigente, experiencia con manuales",
    description: "Pickup diesel confiable y duradera",
    photo:
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&auto=format&fit=crop",
    status: Status.publicado,
  },
];

export default mockProducts;
